---
plugin: gcp_compute
projects:
  - infra-219509
scopes:
  - https://www.googleapis.com/auth/compute
service_account_file: my_project_key.json
filters:
auth_kind: serviceaccount
keyed_groups:
  # Create groups from GCE tags
   - prefix: tag
     key: tags['items']
hostnames:
 # List host by name instead of the default public ip
 - name
compose:
 # Set an inventory parameter to use the Public IP address to connect to the host
 # For Private ip use "networkInterfaces[0].networkIP"
 ansible_host: networkInterfaces[0].accessConfigs[0].natIP

