---
- name: Update and upgrade repo and install ruby
  hosts: all
  become: true
  tasks:
    - name: update repo  
      apt:
        upgrade: yes
        update_cache: yes
    - name: install rubby
      apt:     
        name: "{{ packages }}"
      vars:
        packages:
        - ruby-full
        - ruby-bundler
        - build-essential
